apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mesh-apps
spec:
  selector: {matchLabels: {app: backend}}
  template:
    metadata: {labels: {app: backend}}
    spec:
      nodeSelector: {workload: backend}
      containers:
      - name: app
        image: hashicorp/http-echo
        args: ["-text", "I am the Backend API"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mesh-apps
spec:
  ports: [{port: 80, targetPort: 5678}]
  selector: {app: backend}
